name: Lint

on:
  pull_request:
    branches: [main, development]
  push:
    branches: [main, development]

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          npm install -g prettier

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
